---
- hosts: all
  become: yes
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
   
    - name: add apt key for nodesource
      apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

    - name: add repo for nodesource
      apt_repository:
            repo: 'deb https://deb.nodesource.com/node_12.x {{ ansible_distribution_release }} main' 
            state: present
            update_cache: yes

    - name: install nodejs
      apt: name=nodejs
    - name: Creates directory
      file:
        path: /node-app
        state: directory
        mode: 0777
    - name: Copy app assets
      copy:
        src: ../app
        dest: /node-app

    - name: Install packages based on package.json using the npm installed with nvm v0.10.1.
      community.general.npm:
        path: /node-app/app
        state: present
    
    - name: Install forever package
      community.general.npm:
        name: forever
        global: yes
    - name: Run node app
      ansible.builtin.shell: forever start /node-app/app/app.js