---
- name: Nginx installation
  hosts: all
  become: yes
  tasks:  
    - name: Update apt-get repo and cache
      ansible.builtin.apt: 
        update_cache: yes 
        force_apt_get: yes 
        cache_valid_time: 3600
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present